name: Test Selenide

on: workflow_dispatch

jobs:
  create-an-account:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2gb

    steps:
      - uses: actions/checkout@v3
      - name: Build with Maven
        run: CUCUMBER_FILTER_TAGS="@CreateAnAccount" mvn test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cucumber-create-an-account
          path: target/cucumber-report.html
  sign-in:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2gb

    steps:
      - uses: actions/checkout@v3
      - name: Build with Maven
        run: CUCUMBER_FILTER_TAGS="@SignIn" mvn test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cucumber-sign-in
          path: target/cucumber-report.html