name: Test Selenide

on: workflow_dispatch

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2gb

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml